[package]
name = "tetris"
version = "0.1.0"
authors = ["Mike <certexplay@gmail.com>"]
edition = "2018"

[dependencies]
ggez = "0.5.0-rc.1"
piston = "0.42.0"
piston_window = "0.89.0"
piston2d-opengl_graphics = "0.59.0"
piston2d-graphics = "0.30.0"
piston2d-touch_visualizer = "0.16.0"
rand = "0.6"
